[workspace]

members = [
  "cookbook",
  "crates/gremlin",
  "crates/mogwai-chan",
  "crates/mogwai-html-macro",
  "crates/mogwai-hydrator",
  "examples/focus-follower",
  "examples/list-of-gizmos",
  "examples/multipage",
  "examples/sandbox",
  "examples/spa-routing",
  "examples/svg",
  "examples/todomvc",
  "mogwai",
]


[profile.release]
lto = true
opt-level = 'z'
