[workspace]

members = [
  "cookbook",
  "crates/mogwai",
  "crates/mogwai-html-macro",
  "crates/mogwai-hydrator",
  "examples/counter",
  "examples/nested-components",
  #"examples/focus-follower",
  "examples/list-of-gizmos",
  #"examples/multipage",
  #"examples/sandbox",
  #"examples/spa-routing",
  "examples/svg",
  "examples/todomvc",
]


[profile.release]
lto = true
opt-level = 'z'
