[workspace]

members = [
  "cookbook",
  "crates/mogwai",
  "crates/mogwai-dom",
  "crates/mogwai-macros",
  "examples/counter",
  "examples/nested-components",
  #"examples/focus-follower",
  "examples/list-of-gizmos",
  #"examples/multipage",
  #"examples/sandbox",
  "examples/spa-routing",
  "examples/svg",
  "examples/todomvc",
  "crates/xtask",
]

exclude = [
  "gentest"
]

resolver = "2"


[profile.release]
lto = true
opt-level = 'z'
