[package]
name = "mogwai-design"
version = "0.1.0"
authors = ["Schell Scivally <efsubenovex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shrev = "1.1.1"
console_log = "0.1.2"
crossbeam = "0.7.3"
log = "0.4"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.31"
features = [
  "CharacterData",
  "CssStyleDeclaration",
  "Document",
  "Element",
  "Event",
  "EventTarget",
  "HtmlElement",
  "Node",
  "Text",
  "Window"
]
