[package]
name = "mogwai"
version = "0.6.0"
authors = ["Schell Scivally <efsubenovex@gmail.com>"]
edition = "2018"
license = "MIT"
description = "The minimal, obvious, graphical, widget application interface."
documentation = "https://docs.rs/mogwai/"
repository = "https://github.com/schell/mogwai"
readme = "../../README.md"
keywords = ["ui", "dom", "app", "reactive", "frontend"]
categories = ["gui", "asynchronous", "widgets"]

[features]
default = ["dom"]
dom = ["mogwai-dom", "mogwai-html-macro/dom"]

[dependencies]
mogwai-core = { path = "../mogwai-core", version = "^0.1" }
mogwai-dom = { path = "../mogwai-dom", version = "^0.1", optional = true }
mogwai-html-macro = { path = "../mogwai-html-macro", version = "^0.3" }

[dev-dependencies]
doc-comment = "^0.3"
smol = "^1.2"

[dev-dependencies.web-sys]
version = "^0.3"
features = ["HtmlElement"]
