[book]
authors = ["Schell Carl Scivally"]
language = "en"
multilingual = false
src = "src"
title = "Cooking with Mogwai"

[preprocessor.variables.variables]
mogwai_docs_version = "0.5.0"
cookbookroot = ""

[output.html]

[output.linkcheck]