name: "on push master"

on:
  push:
    branches: master

jobs:
  publish-cookbook-on-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-cookbook-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-all-refs/heads/master
          ${{ runner.os }}-cargo-all-
          ${{ runner.os }}-cargo-all-

    - name: "publish cookbook to zyghost.com"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: scripts/release_cookbook.sh
