name: "on tag"

on:
  push:
    tags: v*.*.*

jobs:
  publish-crates-on-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-all-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-all-refs/heads/master
          ${{ runner.os }}-cargo-all-

    - name: "publish crates to crates-io"
      run: scripts/release.sh ${{ secrets.cargo_token }}

  publish-cookbook-on-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
        key: ${{ runner.os }}-cargo-all-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-all-refs/heads/master
          ${{ runner.os }}-cargo-all-

    - name: "publish cookbook to zyghost.com"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: scripts/release_cookbook.sh
