name: "test"

on:
  push

jobs:
  test-and-build-mogwai:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v1

    # caching
    - name: Cache .cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo
          /usr/share/rust/.cargo/bin
          target
        key: ${{ runner.os }}-cargo-all-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-cargo-all-refs/heads/master
          ${{ runner.os }}-cargo-all-

    - name: bootstrap
      run: scripts/bootstrap.sh

    - name: test
      run: cargo xtask -vv test

    - name: build
      run: cargo xtask -vv build cookbook
